name: Build and Start Node.js Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Specify the Node.js version you need

      - name: List repository contents
        run: ls -al  # List the contents of the repository for debugging

      - name: Install dependencies
        run: npm install  # This step installs all dependencies listed in package.json

      - name: Build project
        run: npm run build  # This runs the build script defined in package.json, if any

      - name: Start server
        run: npm start  # This starts the server using the start script defined in package.json
