name: Build, Start, and Test Node.js Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Führe die Tests aus

      - name: Start server with PM2
        run: |
          npm install -g pm2  # Installiere PM2
          pm2 start index.js --name "my-app"  # Starte die Anwendung mit PM2
          pm2 save  # Speichere die Prozessliste
          pm2 logs  # Zeige die Logs an (optional)
